name: ClearLagg
main: clearlagg\Loader
version: 1.0.0
api: 4.0.0
website: https://github.com/LegendOfMCPE/ClearLagg
permissions:
    clearlagg.command:
        default: op
        description: "Access to the command feature"

